### ISSUE TITLE
[Request] Please create a library to support dart server / cli

### ISSUE THREAD

**Issue by azkadev** [Telosnex/fonnx#1]
it would be great if your library could run without flutter / gui, sorry if this is a hassle for you

**Comment by jpohhhh** [comment]
This is a really clever way to think of it...I didn't realize till you mentioned it, but there's ~0 difference between using this for inference on a server and the way I was using Python to run inference on Hugging Face.

Dumb question, honestly, I haven't looked into it myself yet:
What prevents this from being used in a pure Dart context?

**Comment by flutter-painter** [comment]
This would require removing all platform-specific logic :

- defaultTargetPlatform calls (in getEmbedding) is specific to Flutter
- MethodChannel also seems flutter specific
- Web stuff is flutter specific

So this would require splitting this package into two with : 

- a core layer in pure Dart including
  - ffi_bindings
  - DartNativeFunctions 
  - OrtSessionObjects stripped of platform specific getters
  - tokenizers
  - ort_minilm_isolate
  - vector
- a Flutter package built on top with the remaining logic related to each platform



[pubspec_dart_only_yaml.txt](https://github.com/nmfisher/flutter_sherpa_onnx/files/13404696/pubspec_dart_only_yaml.txt)

**Comment by azkadev** [comment]
I tried it a few days ago, and managed to run without flutter, I just tried whisper because I only need whisper

This is an open source project I made: https://github.com/azkadev/onnx
