### ISSUE TITLE
[Suggestion] Add Tags in the repo, so that it has a wider reach

### ISSUE THREAD

**Issue by developerfyp** [Telosnex/fonnx#3]
The ai and ml libraries running offline using dart are currently few / almost non-existent, I want you to add tags so that your repo has a wider reach, so that the development of flutter ai will be even better

**Comment by jpohhhh** [comment]
Great idea, thank you, I'm a Github noob and didn't know this was a thing

**Comment by jpohhhh** [comment]
And done!
