### ISSUE TITLE
difference with onnxruntime_flutter ?

### ISSUE THREAD

**Issue by flutter-painter** [Telosnex/fonnx#5]
Could you please explain how fonnx differs from onnxruntime_flutter/ ?
https://github.com/gtbluesky/onnxruntime_flutter/tree/main

**Comment by md-rifatkhan** [comment]
Have you got any answer?

**Comment by jpohhhh** [comment]
Oh that's cool! 

Few differences as of today (Nov 19th 2023)
- no Mac/Windows/Linux/web
- more clean in the sense it's _just_ ONNX
- less helpful in that, when you run inference, you ~always end up needing some ancillary code (ex. we could think of MiniLM as f(String), but it's actually f(tokenizer(String))

Anything else I'd add would veer towards unfair (ex. testing)

Apologies for delay, when I saw this in my email inbox at first, thought it was about the empty [onnx_dart pub package](https://github.com/ArishSultan/onnx_dart)

**Comment by flutter-painter** [comment]
Hi James, thank you for answering,
No rush here :) 
I understood that fonnx supports all platforms but was afraid of a trade-offs / limitations.
I get that they are none and will explore it further
